language: perl

install:
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - cpanm -n Test::CPAN::Changes Test::EOL Test::Fixme Test::NoTabs Test::Pod::Spelling::CommonMistakes Test::Spelling Test::Strict Test::Version Test::Vars || true
  - cpanm -n Alien::Base

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"

script:
  - dzil test

env:
  - ALIEN_FORCE=1
  - ALIEN_FORCE=0
